
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace barApp
{

using System;
    using System.Collections.Generic;
    
public partial class DetallesVentaEspecial
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DetallesVentaEspecial()
    {

        this.DetalleVenta1 = new HashSet<DetalleVenta>();

    }


    public int idEspecial { get; set; }

    public Nullable<decimal> idVenta { get; set; }

    public string idProducto { get; set; }

    public Nullable<int> cantidad { get; set; }

    public Nullable<int> idCuadre { get; set; }

    public Nullable<int> idDetalle { get; set; }

    public Nullable<decimal> precioEntrada { get; set; }



    public virtual Cuadre Cuadre { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Venta Venta { get; set; }

    public virtual DetalleVenta DetalleVenta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleVenta> DetalleVenta1 { get; set; }

}

}
