
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace barApp
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleVenta
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DetalleVenta()
    {

        this.DetallesVentaEspecial = new HashSet<DetallesVentaEspecial>();

    }


    public int idDetalle { get; set; }

    public decimal idVenta { get; set; }

    public float subTotal { get; set; }

    public string idProducto { get; set; }

    public int cantidad { get; set; }

    public Nullable<bool> despachada { get; set; }

    public Nullable<decimal> precioVenta { get; set; }

    public Nullable<decimal> precioEntrada { get; set; }

    public Nullable<bool> espcial { get; set; }

    public Nullable<int> idEspecial { get; set; }



    public virtual Producto Producto { get; set; }

    public virtual Venta Venta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetallesVentaEspecial> DetallesVentaEspecial { get; set; }

    public virtual DetallesVentaEspecial DetallesVentaEspecial1 { get; set; }

}

}
