
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace barApp
{

using System;
    using System.Collections.Generic;
    
public partial class Factura
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Factura()
    {

        this.Creditos = new HashSet<Creditos>();

    }


    public decimal numFactura { get; set; }

    public System.DateTime fecha { get; set; }

    public float IVA { get; set; }

    public float total { get; set; }

    public int numPago { get; set; }

    public Nullable<decimal> descuento { get; set; }

    public Nullable<decimal> idVenta { get; set; }

    public bool TieneCedito { get; set; }

    public string rnc { get; set; }

    public string ncf { get; set; }



    public virtual ModoPago ModoPago { get; set; }

    public virtual Venta Venta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Creditos> Creditos { get; set; }

}

}
