//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impresoras
    {
        public int @int { get; set; }
        public string Ubicacion { get; set; }
        public string IpPC { get; set; }
        public string IpImpresora { get; set; }
        public Nullable<bool> defecto { get; set; }
    }
}
