//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Inventario = new HashSet<Inventario>();
            this.InventarioBar = new HashSet<InventarioBar>();
            this.DetalleVenta = new HashSet<DetalleVenta>();
            this.DetallesVentaEspecial = new HashSet<DetallesVentaEspecial>();
            this.ProductoEliminado = new HashSet<ProductoEliminado>();
        }
    
        public string idProducto { get; set; }
        public string nombre { get; set; }
        public decimal precioVenta { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<decimal> precioAlmacen { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<decimal> precioFiesta { get; set; }
        public string idProductoEspecial { get; set; }
        public string idProductoEspecialCantidad { get; set; }
        public Nullable<bool> especial { get; set; }
        public string iniciolEspecial { get; set; }
        public string finalEspecial { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioBar> InventarioBar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesVentaEspecial> DetallesVentaEspecial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoEliminado> ProductoEliminado { get; set; }
    }
}
